# =============================================================================
# Tests: Módulo Data — Aurora Serverless v2, S3, KMS, Secrets Manager
# Ejecución: ./scripts/run-tests-localstack.sh
# =============================================================================

provider "aws" {
  region                      = "us-east-1"
  skip_credentials_validation = true
  skip_requesting_account_id  = true
  skip_metadata_api_check     = true
  access_key                  = "mock_access_key"
  secret_key                  = "mock_secret_key"
}

variables {
  pais                   = "ar"
  entorno                = "prod"
  vpc_id                 = "vpc-test-123"
  data_subnet_ids        = ["subnet-data-1", "subnet-data-2"]
  ecs_security_group_id  = "sg-ecs-test"
  aurora_min_acu         = 0.5
  aurora_max_acu         = 4
  aurora_database_name   = "hce"
  aurora_master_username = "hce_admin"
  s3_buckets             = ["estudios-medicos", "adjuntos-facturacion"]
  backup_retention_days  = 7
}

# -----------------------------------------------------------------------------
# Test 1: Aurora Serverless v2 se crea con motor PostgreSQL
# -----------------------------------------------------------------------------
run "aurora_postgresql_engine" {
  command = plan

  assert {
    condition     = aws_rds_cluster.this.engine == "aurora-postgresql"
    error_message = "Aurora debe usar motor aurora-postgresql"
  }

  assert {
    condition     = aws_rds_cluster.this.engine_mode == "provisioned"
    error_message = "Aurora debe estar en modo provisioned (requerido para Serverless v2)"
  }
}

# -----------------------------------------------------------------------------
# Test 2: Aurora tiene cifrado habilitado con KMS
# -----------------------------------------------------------------------------
run "aurora_encrypted_with_kms" {
  command = plan

  assert {
    condition     = aws_rds_cluster.this.storage_encrypted == true
    error_message = "Aurora debe tener storage cifrado con KMS"
  }
}

# -----------------------------------------------------------------------------
# Test 3: Aurora tiene logging de PostgreSQL habilitado
# -----------------------------------------------------------------------------
run "aurora_postgresql_logging" {
  command = plan

  assert {
    condition     = contains(aws_rds_cluster.this.enabled_cloudwatch_logs_exports, "postgresql")
    error_message = "Aurora debe exportar logs de PostgreSQL a CloudWatch"
  }
}

# -----------------------------------------------------------------------------
# Test 4: Credenciales de Aurora en Secrets Manager (no hardcodeadas)
# -----------------------------------------------------------------------------
run "aurora_credentials_in_secrets_manager" {
  command = plan

  assert {
    condition     = aws_secretsmanager_secret.aurora.name != ""
    error_message = "Las credenciales de Aurora deben estar en Secrets Manager"
  }
}

# -----------------------------------------------------------------------------
# Test 5: Password de Aurora es autogenerado (32 caracteres)
# -----------------------------------------------------------------------------
run "aurora_password_autogenerated" {
  command = plan

  assert {
    condition     = random_password.aurora_master.length == 32
    error_message = "El password de Aurora debe tener 32 caracteres"
  }

  assert {
    condition     = random_password.aurora_master.special == false
    error_message = "El password no debe tener caracteres especiales (para connection strings)"
  }
}

# -----------------------------------------------------------------------------
# Test 6: Security Group permite tráfico solo desde ECS
# -----------------------------------------------------------------------------
run "aurora_security_group_restricted" {
  command = plan

  assert {
    condition     = contains([for i in aws_security_group.aurora.ingress : i.from_port], 5432)
    error_message = "Security Group debe permitir tráfico en puerto 5432"
  }

  assert {
    condition     = length(aws_security_group.aurora.ingress) == 1
    error_message = "Solo debe haber una regla de ingreso (desde ECS)"
  }
}

# -----------------------------------------------------------------------------
# Test 7: Se crean 2 buckets S3 (estudios + adjuntos)
# -----------------------------------------------------------------------------
run "s3_buckets_created" {
  command = plan

  assert {
    condition     = length(aws_s3_bucket.this) == 2
    error_message = "Deben existir 2 buckets S3"
  }
}

# -----------------------------------------------------------------------------
# Test 8: KMS key se crea para cifrado
# -----------------------------------------------------------------------------
run "kms_key_created" {
  command = plan

  assert {
    condition     = aws_kms_key.this.description != ""
    error_message = "KMS key debe ser creada con descripción"
  }
}

# -----------------------------------------------------------------------------
# Test 9: En prod, Aurora tiene 2 instancias (writer + reader)
# -----------------------------------------------------------------------------
run "aurora_prod_instances" {
  command = plan

  assert {
    condition     = aws_rds_cluster_instance.this[0].instance_class == "db.serverless"
    error_message = "Las instancias de Aurora deben usar db.serverless"
  }
}
